// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf08cL-3qUW3qeXiBJkMKPL8C8Kh_qG8c',
    appId: '1:813465753814:web:55d009fe75bade609a5177',
    messagingSenderId: '813465753814',
    projectId: 'flutter-e-ticaret',
    authDomain: 'flutter-e-ticaret.firebaseapp.com',
    storageBucket: 'flutter-e-ticaret.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWar57lq0m0y1C--McxeV0qP7r7ob07ug',
    appId: '1:813465753814:android:f7986ba2805a78cb9a5177',
    messagingSenderId: '813465753814',
    projectId: 'flutter-e-ticaret',
    storageBucket: 'flutter-e-ticaret.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8i2jXi0cdihFjv0_yRJC-fWICOWJ_QMQ',
    appId: '1:813465753814:ios:5491f1096bce9fee9a5177',
    messagingSenderId: '813465753814',
    projectId: 'flutter-e-ticaret',
    storageBucket: 'flutter-e-ticaret.appspot.com',
    iosClientId: '813465753814-ms7eqid9e7i5j0gtevuhpo9oprl0hm1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterETicaret',
  );
}
